[build]
  # Команда для сборки проекта
  command = "npm run build"
  
  # Директория с готовыми статическими файлами
  publish = "out"

[build.environment]
  # Node.js версия
  NODE_VERSION = "18"
  # Переменные окружения для сборки
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

# Настройки для SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Обработка статических файлов
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# Кеширование статических ресурсов
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
